import { PrismaClient, Task, Prisma } from '@prisma/client';
import { PrismaClientKnownRequestError } from '@prisma/client/runtime/library';

const prisma = new PrismaClient();

// Define the expected shape of the parameters more explicitly
// This helps ensure the data passed to Prisma is correct.
// Note: This is illustrative; the actual validation happens via the Zod schema
// generated by dynamicToolSchema.ts before this function is called.
export interface UpdateTaskParams {
  task_id: string;
  [key: string]: any; // Allow other optional fields based on TASK_FIELD_CONFIG
}

// Define the result shape for tool execution
export interface ToolExecutionResult {
  success: boolean;
  message: string;
  data?: Partial<Task> | null;
  error?: string;
}

/**
 * Executes the update operation for task fields.
 * Handles data transformation (e.g., date strings to Date objects) before updating.
 * Attempts to find the task by primary CUID id first, then by optional task_id if necessary.
 * @param params - The parameters containing the task identifier and fields to update.
 * @returns An object indicating success or failure, with the updated task or an error message.
 */
export async function executeUpdateTaskFields(params: UpdateTaskParams): Promise<ToolExecutionResult> {
  // Extract the identifier provided by the AI (which *should* be the CUID 'id' based on tool description)
  // and the rest of the fields to update.
  const { task_id: providedIdentifier, ...fieldsToUpdate } = params;

  console.log(`[executeUpdateTaskFields] Received request to update task with identifier: ${providedIdentifier}`);
  console.log('[executeUpdateTaskFields] Fields to update (raw):', fieldsToUpdate);

  if (!providedIdentifier) {
    return { success: false, message: 'Task identifier (task_id) is required.' };
  }

  let taskToUpdate: Task | null = null;
  let targetCuid: string | null = null;

  try {
    // 1. Try finding the task by primary ID (CUID) first
    console.log(`[executeUpdateTaskFields] Attempting lookup by primary ID: ${providedIdentifier}`);
    taskToUpdate = await prisma.task.findUnique({
      where: { id: providedIdentifier },
    });

    if (taskToUpdate) {
      console.log(`[executeUpdateTaskFields] Found task by primary ID.`);
      targetCuid = taskToUpdate.id;
    } else {
      // 2. If not found by primary ID, try finding by the optional task_id
      console.log(`[executeUpdateTaskFields] Not found by primary ID. Attempting lookup by optional task_id: ${providedIdentifier}`);
      taskToUpdate = await prisma.task.findUnique({
        where: { task_id: providedIdentifier },
      });

      if (taskToUpdate) {
        console.log(`[executeUpdateTaskFields] Found task by optional task_id. Using its primary CUID: ${taskToUpdate.id}`);
        targetCuid = taskToUpdate.id; // Get the actual CUID 'id' for the update
      } else {
        console.log(`[executeUpdateTaskFields] Task not found by either primary id or optional task_id.`);
        return {
          success: false,
          message: `Task not found with identifier: ${providedIdentifier}. Could not find by primary 'id' or optional 'task_id'.`,
        };
      }
    }

    // 3. Transform data before sending to Prisma
    const transformedData = transformUpdateData(fieldsToUpdate);
    console.log('[executeUpdateTaskFields] Transformed data for Prisma:', transformedData);

    // 4. Perform the update using the confirmed target CUID
    console.log(`[executeUpdateTaskFields] Updating task with confirmed CUID: ${targetCuid}`);
    const updatedTask = await prisma.task.update({
      where: { id: targetCuid }, // Use the confirmed CUID 'id'
      data: transformedData,
    });

    console.log(`[executeUpdateTaskFields] Successfully updated task ${targetCuid}`);
    return { success: true, data: updatedTask, message: 'Task updated successfully.' };

  } catch (error: any) {
    console.error(`[executeUpdateTaskFields] Error updating task ${targetCuid ?? providedIdentifier}:`, error);

    let errorMessage = 'An unexpected error occurred during update.';
    if (error instanceof Prisma.PrismaClientKnownRequestError) {
      // Provide more specific Prisma error messages
      errorMessage = `Prisma Error (${error.code}): ${error.message.split('\n').pop()?.trim() ?? 'Failed to update task.'}`;
      if (error.code === 'P2002') {
        errorMessage = `Prisma Error (P2002): A unique constraint failed (e.g., duplicate task_id if it's unique).`;
      }
      // Keep the P2025 check, although our lookup should prevent it now
      if (error.code === 'P2025') {
         errorMessage = `Prisma Error (P2025): Record to update not found. This should not happen after lookup. Target CUID: ${targetCuid}`; 
      }
    } else if (error instanceof Error) {
      errorMessage = error.message;
    }

    return {
      success: false,
      message: errorMessage,
      error: error.stack, // Include stack trace for debugging
    };
  }
}

/**
 * Helper function to transform update data (e.g., date strings to Date objects)
 * and filter out undefined values to prevent accidental clearing of fields.
 */
function transformUpdateData(data: Record<string, any>): Record<string, any> {
    const filteredData: Record<string, any> = {};

    for (const key in data) {
        if (Object.prototype.hasOwnProperty.call(data, key)) {
            const value = data[key];

            // Skip fields with undefined values entirely
            if (value === undefined) {
                continue;
            }

            // Preserve null values (used for explicitly clearing fields)
            // Transform date/datetime strings to Date objects if they are valid
            if ((key === 'due_date' || key === 'start_date' || key === 'completion_date') && typeof value === 'string') {
                const date = new Date(value);
                // Check if the date is valid before assigning
                if (!isNaN(date.getTime())) {
                    filteredData[key] = date;
                } else {
                    // Handle invalid date strings if necessary (e.g., log, skip, or keep as string)
                    console.warn(`[transformUpdateData] Invalid date string for ${key}: ${value}. Skipping transformation.`);
                    // Decide whether to keep the original invalid string or skip the field
                    // filteredData[key] = value; // Option: Keep original string
                }
            } else if (key === 'created_at' || key === 'last_modified_at') {
                // Potentially handle other datetime fields if needed, though these are usually auto-managed
                const date = new Date(value);
                if (!isNaN(date.getTime())) {
                     filteredData[key] = date;
                } else {
                    console.warn(`[transformUpdateData] Invalid datetime string for ${key}: ${value}. Skipping transformation.`);
                }
            } else {
                // Keep other values (including null, numbers, strings, booleans, arrays)
                filteredData[key] = value;
            }
        }
    }

    console.log('[transformUpdateData] Original data:', data);
    console.log('[transformUpdateData] Filtered & Transformed data:', filteredData);
    return filteredData;
}
