import { PrismaClient, Task, Prisma } from '@prisma/client';
import { PrismaClientKnownRequestError } from '@prisma/client/runtime/library';

const prisma = new PrismaClient();

// Define the expected shape of the parameters more explicitly
// This helps ensure the data passed to Prisma is correct.
// Note: This is illustrative; the actual validation happens via the Zod schema
// generated by dynamicToolSchema.ts before this function is called.
export interface UpdateTaskParams {
  task_id: string;
  [key: string]: any; // Allow other optional fields based on TASK_FIELD_CONFIG
}

// Define the result shape for tool execution
export interface ToolExecutionResult {
  success: boolean;
  message: string;
  data?: Partial<Task> | null;
  error?: string;
}

/**
 * Executes the update operation for task fields.
 * Handles data transformation (e.g., date strings to Date objects) before updating.
 * Attempts to find the task by primary CUID id first, then by optional task_id if necessary.
 * @param params - The parameters containing the task identifier and fields to update.
 * @returns An object indicating success or failure, with the updated task or an error message.
 */
export async function executeUpdateTaskFields(params: UpdateTaskParams): Promise<ToolExecutionResult> {
  // Extract the identifier provided by the AI (which *should* be the CUID 'id' based on tool description)
  // and the rest of the fields to update.
  const { task_id: providedIdentifier, ...fieldsToUpdate } = params;

  console.log(`[executeUpdateTaskFields] Received request to update task with identifier: ${providedIdentifier}`);
  console.log('[executeUpdateTaskFields] Fields to update (raw):', fieldsToUpdate);

  if (!providedIdentifier) {
    return { success: false, message: 'Task identifier (task_id) is required.' };
  }

  let taskToUpdate: Task | null = null;
  let targetCuid: string | null = null;

  try {
    // 1. Try finding the task by primary ID (CUID) first
    console.log(`[executeUpdateTaskFields] Attempting lookup by primary ID: ${providedIdentifier}`);
    taskToUpdate = await prisma.task.findUnique({
      where: { id: providedIdentifier },
    });

    if (taskToUpdate) {
      console.log(`[executeUpdateTaskFields] Found task by primary ID.`);
      targetCuid = taskToUpdate.id;
    } else {
      // 2. If not found by primary ID, try finding by the optional task_id
      console.log(`[executeUpdateTaskFields] Not found by primary ID. Attempting lookup by optional task_id: ${providedIdentifier}`);
      taskToUpdate = await prisma.task.findUnique({
        where: { task_id: providedIdentifier },
      });

      if (taskToUpdate) {
        console.log(`[executeUpdateTaskFields] Found task by optional task_id. Using its primary CUID: ${taskToUpdate.id}`);
        targetCuid = taskToUpdate.id; // Get the actual CUID 'id' for the update
      } else {
        console.log(`[executeUpdateTaskFields] Task not found by either primary id or optional task_id.`);
        return {
          success: false,
          message: `Task not found with identifier: ${providedIdentifier}. Could not find by primary 'id' or optional 'task_id'.`,
        };
      }
    }

    // 3. Transform data before sending to Prisma
    const transformedData = transformUpdateData(fieldsToUpdate);
    console.log('[executeUpdateTaskFields] Transformed data for Prisma:', transformedData);

    // 4. Perform the update using the confirmed target CUID
    console.log(`[executeUpdateTaskFields] Updating task with confirmed CUID: ${targetCuid}`);
    const updatedTask = await prisma.task.update({
      where: { id: targetCuid }, // Use the confirmed CUID 'id'
      data: transformedData,
    });

    console.log(`[executeUpdateTaskFields] Successfully updated task ${targetCuid}`);
    return { success: true, data: updatedTask, message: 'Task updated successfully.' };

  } catch (error: any) {
    console.error(`[executeUpdateTaskFields] Error updating task ${targetCuid ?? providedIdentifier}:`, error);

    let errorMessage = 'An unexpected error occurred during update.';
    if (error instanceof Prisma.PrismaClientKnownRequestError) {
      // Provide more specific Prisma error messages
      errorMessage = `Prisma Error (${error.code}): ${error.message.split('\n').pop()?.trim() ?? 'Failed to update task.'}`;
      if (error.code === 'P2002') {
        errorMessage = `Prisma Error (P2002): A unique constraint failed (e.g., duplicate task_id if it's unique).`;
      }
      // Keep the P2025 check, although our lookup should prevent it now
      if (error.code === 'P2025') {
         errorMessage = `Prisma Error (P2025): Record to update not found. This should not happen after lookup. Target CUID: ${targetCuid}`; 
      }
    } else if (error instanceof Error) {
      errorMessage = error.message;
    }

    return {
      success: false,
      message: errorMessage,
      error: error.stack, // Include stack trace for debugging
    };
  }
}

// Helper function to transform update data (e.g., date strings to Date objects)
function transformUpdateData(data: Record<string, any>): Record<string, any> {
  const transformedData: Record<string, any> = {};
  for (const [key, value] of Object.entries(data)) {
    // Example: Convert valid ISO date strings to Date objects for Prisma
    // Adjust this logic based on how dates are defined in TASK_FIELD_CONFIG and schema.prisma
    // We check if value is a non-null string that looks like a date.
    if (typeof value === 'string' && (key.includes('date') || key.includes('Date'))) {
        try {
            const dateValue = new Date(value);
            // Check if the date is valid before assigning
            if (!isNaN(dateValue.getTime())) {
                transformedData[key] = dateValue;
            } else {
                // Handle invalid date strings if necessary, maybe skip or log
                console.warn(`[executeUpdateTaskFields] Invalid date string for field ${key}: ${value}`);
                // Optionally, keep the original value or set to null if schema allows
                 transformedData[key] = null; // Assuming nullable field for invalid dates
            }
        } catch (e) {
            console.warn(`[executeUpdateTaskFields] Error parsing date string for field ${key}: ${value}`, e);
            transformedData[key] = null; // Fallback to null on parsing error
        }
    } else if (value === null && (key.includes('date') || key.includes('Date'))) {
        // Explicitly handle null to clear date fields if schema allows nullable DateTime
        transformedData[key] = null;
    } else if (value !== undefined) { // Only include non-undefined values
        transformedData[key] = value;
    }
  }
  return transformedData;
}
